add_test([=[ListaSimplesTest.InserirInicio]=]  /home/ramon/ramon/alg-fabbri-IPRJ-UERJ/alg/list/tests/run-list-tests [==[--gtest_filter=ListaSimplesTest.InserirInicio]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ListaSimplesTest.InserirInicio]=]  PROPERTIES WORKING_DIRECTORY /home/ramon/ramon/alg-fabbri-IPRJ-UERJ/alg/list/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ListaSimplesTest.DeletarInicio]=]  /home/ramon/ramon/alg-fabbri-IPRJ-UERJ/alg/list/tests/run-list-tests [==[--gtest_filter=ListaSimplesTest.DeletarInicio]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ListaSimplesTest.DeletarInicio]=]  PROPERTIES WORKING_DIRECTORY /home/ramon/ramon/alg-fabbri-IPRJ-UERJ/alg/list/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ListaDuplaTest.InserirInicio]=]  /home/ramon/ramon/alg-fabbri-IPRJ-UERJ/alg/list/tests/run-list-tests [==[--gtest_filter=ListaDuplaTest.InserirInicio]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ListaDuplaTest.InserirInicio]=]  PROPERTIES WORKING_DIRECTORY /home/ramon/ramon/alg-fabbri-IPRJ-UERJ/alg/list/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ListaDuplaTest.DeletarInicio]=]  /home/ramon/ramon/alg-fabbri-IPRJ-UERJ/alg/list/tests/run-list-tests [==[--gtest_filter=ListaDuplaTest.DeletarInicio]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ListaDuplaTest.DeletarInicio]=]  PROPERTIES WORKING_DIRECTORY /home/ramon/ramon/alg-fabbri-IPRJ-UERJ/alg/list/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BufferCircularTest.InserirECheio]=]  /home/ramon/ramon/alg-fabbri-IPRJ-UERJ/alg/list/tests/run-list-tests [==[--gtest_filter=BufferCircularTest.InserirECheio]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BufferCircularTest.InserirECheio]=]  PROPERTIES WORKING_DIRECTORY /home/ramon/ramon/alg-fabbri-IPRJ-UERJ/alg/list/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  run-list-tests_TESTS ListaSimplesTest.InserirInicio ListaSimplesTest.DeletarInicio ListaDuplaTest.InserirInicio ListaDuplaTest.DeletarInicio BufferCircularTest.InserirECheio)
